name: mc-server-installer
version: git
summary: Minecraft Server Downloader and Installer
description: |
    A Minecraft Server installer snap.  
grade: stable
confinement: strict

apps:
  mc-server-installer:
    command: python3 $SNAP/server-installer-menu.py
    plugs:
      - network
      - home
      - network-bind

parts:
  mc-server-installer:
    source: https://github.com/kz6fittycent/mc-server-installer
    source-type: git
    plugin: python
    python-version: python3
    
    build-packages:
      - openjdk-8-jre-headless
      - wget
      - python3
      
    stage-packages:
      - openjdk-8-jre-headless
      - wget
      - python3

  publish:
    plugin: copy
    files:
      ./2.sh: 2.sh
      ./4.sh: 4.sh
      ./6.sh: 6.sh
      ./8.sh: 8.sh
      ./12.sh: 12.sh
      ./16.sh: 16.sh
      ./24.sh: 24.sh
      ./server-installer-menu.py: server-installer-menu.py
