name: mc-server-installer
version: '7.1'
summary: Minecraft Server Downloader and Installer/Configuration Tool
description: |
    A Minecraft Server installer and configuration snap that downloads the latest .jar file and allows you to start your server with the amount of RAM you choose. 

base: core18
grade: stable
confinement: strict

apps:
  mc-server-installer:
    command: bash $SNAP/mc-server-installer.sh
    plugs:
      - network
      - home
      - network-bind

parts:
  mc-server-installer:
    source: https://github.com/kz6fittycent/mc-server-installer
    source-type: git
    plugin: nil
    
    build-packages:
      - openjdk-8-jre-headless
      - curl
      - sed
      - jq
      - nano

      
    stage-packages:
      - openjdk-8-jre-headless
      - curl
      - sed
      - jq
      - nano

  publish:
    plugin: dump
    source: .
    organize:
      ./mc-server-installer.sh: mc-server-installer.sh
