name: mc-server-installer
version: git
summary: Minecraft Server Downloader and Installer
description: |
    A Minecraft Server installer snap.  
grade: stable
confinement: strict

apps:
  mc-server-installer:
    command: download-server.py
    plugs:
      - network
      - home
      - network-bind

parts:
  mc-server-installer:
    source: https://github.com/kz6fittycent/mc-server-installer
    source-type: git
    plugin: python
    python-version: python3

    build-packages:
      - openjdk-8-jre-headless
      - python3
      
    stage-packages:
      - openjdk-8-jdk
      - python3

  publish:
    plugin: copy
    files:
      ./download-server.py: download-server.py
