name: mc-server-installer
version: git
summary: Minecraft Server Downloader and Installer
description: |
    A Minecraft Server installer snap. Keeps your server running the latest version of Minecraft. 
grade: stable
confinement: strict

apps:
  mc-server-installer:
    command: java -Xmx1024M -Xms1024M -jar server.jar nogui
    plugs:
      - network
      - home

parts:
  launcher:
    plugin: dump
    source: scripts

  server:
    plugin: nil
    build-packages:
      - openjdk-8-jre-headless
      
    stage-packages:
      - openjdk-8-jre-headless
