name: mc-server-installer
version: git
summary: Minecraft Server Downloader and Installer
description: |
    A Minecraft Server installer snap.  
grade: stable
confinement: strict

apps:
  mc-server-installer:
    command: mc-server-installer.sh
    plugs:
      - network
      - home
      - network-bind

parts:
  mc-server-installer:
    source: https://github.com/kz6fittycent/mc-server-installer
    source-type: git
    plugin: nil
    
    build-packages:
      - openjdk-8-jre-headless
      - wget

      
    stage-packages:
      - openjdk-8-jre-headless
      - wget

  publish:
    plugin: copy
    files:
      ./mc-server-installer.sh: mc-server-installer.sh
