name: mc-server-installer
version: '1.3'
summary: Minecraft Server Downloader and Installer
description: |
    A Minecraft Server installer snap that downloads the latest .jar file and allows you to start your server with the amount of RAM you choose. 
grade: stable
confinement: strict

apps:
  mc-server-installer:
    command: bash $SNAP/mc-server-installer.sh
    plugs:
      - network
      - home
      - network-bind

parts:
  mc-server-installer:
    source: https://github.com/kz6fittycent/mc-server-installer
    source-type: git
    plugin: nil
    
    build-packages:
      - openjdk-8-jre-headless
      - curl
      - sed
      - jq
      - nano

      
    stage-packages:
      - openjdk-8-jre-headless
      - curl
      - sed
      - jq
      - nano

  publish:
    plugin: copy
    files:
      ./mc-server-installer.sh: mc-server-installer.sh
