name: mc-server-installer
version: '7.3'
summary: Minecraft Server Downloader and Installer/Configuration Tool
description: |
    A Minecraft Server installer and configuration snap that downloads the latest .jar file and allows you to start your server with the amount of RAM you choose. 

license: MIT

base: core20
grade: stable
confinement: strict

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf
  - build-on: ppc64el
  - build-on: s390x

apps:
  mc-server-installer:
    command: mc-server-installer
    plugs:
      - network
      - home
      - network-bind

parts:
  mc-server-installer:
    source: https://github.com/kz6fittycent/mc-server-installer
    source-type: git
    plugin: nil
    
    build-packages:
      - openjdk-8-jre-headless
      - curl
      - sed
      - jq
      - nano
      - tar
      
    stage-packages:
      - openjdk-8-jre-headless
      - curl
      - sed
      - jq
      - nano
      - tar

  publish:
    plugin: dump
    source: .
